weather.settings:
  type: config_object
  label: 'Weather module settings'
  mapping:
    api:
      type: mapping
      label: 'API settings'
      mapping:
        key:
          type: string
          label: 'Key'
        enpoint:
          type: string
          label: 'Endpoint'
    location:
      type: mapping
      label: 'Weather location'
      mapping:
        city:
          type: string
          label: 'City'
        country_code:
          type: string
          label: 'Country code'
    other:
      type: mapping
      label: 'Other settings'
      mapping:
        units:
          type: string
          label: 'Units'
        date_format:
          type: string
          label: 'Date format'
